development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: galery_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: galery_development
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
